### ISSUE TITLE
v2.4.0 is causing issues on ownCloud 10.8

### ISSUE THREAD

**Issue by xoxys** [owncloud/files_texteditor#361]
There seems to be an issue after upgrading to v2.4.0 on ownCloud 10.8

```
Exception: {"Exception":"Error","Message":"Call to undefined method OCA\\Files_Texteditor\\AppInfo\\Application::boot()","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/legacy\/app.php(253): require_once()\n#1 \/var\/www\/owncloud\/lib\/private\/legacy\/app.php(192): OC_App::requireAppFile(Object(OCA\\Files_Texteditor\\AppInfo\\Application))\n#2 \/var\/www\/owncloud\/lib\/private\/legacy\/app.php(125): OC_App::loadApp('files_textedito...')\n#3 \/var\/www\/owncloud\/lib\/base.php(912): OC_App::loadApps()\n#4 \/var\/www\/owncloud\/index.php(54): OC::handleRequest()\n#5 {main}","File":"\/usr\/local\/src\/owncloud\/custom\/files_texteditor\/appinfo\/app.php","Line":6}
```

**Comment by stilltldr** [comment]
Hi,

maybe related, since the update, I cannot access the webinterface anymore. Not a docker instance. Logs say:

`TypeError: Return value of OCA\Files_Texteditor\AppInfo\Application::registerEventHooks() must be an instance of OCA\Files_Texteditor\AppInfo\void, none returned at /PATH/TO/WWW/DIR/owncloud10/apps/files_texteditor/appinfo/application.php#73`

**Comment by stilltldr** [comment]
PS: had to disable the TextEditor to access the web interface again
